// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUJC_d_WAdTMPyagr0r0vYsi6NPjdQz8k',
    appId: '1:639527766832:web:75fa6809145069a5b896f5',
    messagingSenderId: '639527766832',
    projectId: 'salud-3e2f6',
    authDomain: 'salud-3e2f6.firebaseapp.com',
    storageBucket: 'salud-3e2f6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJa6rrL5ZnUuTAl1iux99m-ltS7-c5g1c',
    appId: '1:639527766832:android:81dd729556944732b896f5',
    messagingSenderId: '639527766832',
    projectId: 'salud-3e2f6',
    storageBucket: 'salud-3e2f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGXUupsvDoP9oBjOWdtOfD4W-4LkgNEtM',
    appId: '1:639527766832:ios:2ac3e62c40a2819bb896f5',
    messagingSenderId: '639527766832',
    projectId: 'salud-3e2f6',
    storageBucket: 'salud-3e2f6.appspot.com',
    iosBundleId: 'com.example.saludEficiente',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGXUupsvDoP9oBjOWdtOfD4W-4LkgNEtM',
    appId: '1:639527766832:ios:f9f792f9dde2c019b896f5',
    messagingSenderId: '639527766832',
    projectId: 'salud-3e2f6',
    storageBucket: 'salud-3e2f6.appspot.com',
    iosBundleId: 'com.example.saludEficiente.RunnerTests',
  );
}
